Add welcome intro to panel extension (Issue #53)
alveusgg/extension pull request #154
Opened 2024-02-01 03:06 UTC by umami-umami

## Overview

This PR resolves issue #53 to add the welcome intro that is used in the overlay extension to the panel extension. A button was added to the nav bar of the panel app. Clicking the button displays the welcome card as an overlay. 

## Changes 
* Moved `Welcome` component from overlay extension components to shared components
* Modified `Welcome` social icons to allow overflow for small screens
* Added info icon as a button in the nav component 
* Created new component in the panel that re-uses the shared `Welcome` component 
* Show / hide the new welcome overlay component in the panel based on button click

## Screenshots

<details>

<summary>Panel</summary>

<img width="684" alt="Screen Shot 2024-01-31 at 4 44 18 PM" src="https://github.com/alveusgg/extension/assets/924208/85f4211d-8fff-46f4-aea6-fab31e545fd1">

</details>
<details>

<summary>Mobile (Small screen)</summary>

<img width="637" alt="Screen Shot 2024-01-31 at 4 43 16 PM" src="https://github.com/alveusgg/extension/assets/924208/5c722715-04c3-467f-8bd9-c0dffcf850c8">

</details>
<details>

<summary>Video Overlay</summary>

<img width="657" alt="Screen Shot 2024-01-31 at 4 44 48 PM" src="https://github.com/alveusgg/extension/assets/924208/6cae7b1a-bfaa-4a1d-a660-c4a611e33522">

</details>

2024-02-01 03:07 UTC, umami-umami commented on src/pages/panel/components/nav/Nav.tsx
> +      <div className={styles.filler} />
I'm admittedly pretty new to web dev, so I'm not sure if there's a better way to make the info icon right-aligned while maintaining the center justification of the logo and nav title. LMK if there's something better I can do.

2024-02-04 04:00 UTC, MattIPv4 requested changes
This is generally looking great and is what I had in mind for this! Most of my comments are nits :)

One general thing (couldn't find a logical place in the files to leave the comment), could we add a transition when the overlay is rendered on the panel, the same as the cards (they slide in)?

2024-02-04 04:08 UTC, MattIPv4 commented on src/pages/panel/components/nav/nav.module.scss
> +  }
I think with this change things might still be a bit funky just due to the sheer tiny screen size that Twitch shows the panel on -- we might need to add a media query to the nav styling to account for that:

```diff
- justify-content: center;
- width: 100vw;
- padding: 0.5rem;
+ justify-content: start;
+ right: 0;
+ left: 0;
+ padding: 0.5rem calc(2rem + 0.5rem + 20px) 0.5rem 0.5rem; // account for info button (right only)
+ 
+ @media (min-width: 25rem) {
+   justify-content: center;
+   padding: 0.5rem calc(2rem + 0.5rem + 20px); // account for info button (balanced)
+ }
```

I _think_ this should result in the logo/heading being on the left for the Twitch panel width, and then being centered once there is space if the panel ever ended up on a bigger screen

2024-02-04 23:06 UTC, umami-umami commented on src/pages/panel/components/nav/nav.module.scss
> +  }
Nice! Looks like that worked as you intended. In really small screen sizes, the logo/heading is on the left.

2024-02-05 03:30 UTC, MattIPv4 approved these changes
LGTM, tyvm

2024-02-05 03:31 UTC, merged